### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by survivant** [b3er/idea-archive-browser#34]
````
IntelliJ IDEA 2022.2 RC (Ultimate Edition)
Build #IU-222.3345.90, built on July 20, 2022
Subscription is active until November 21, 2022.
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Non-Bundled Plugins:
    org.jetbrains.plugins.go-template (222.3345.90)
    com.github.b3er.idea.plugins.arc.browser (0.32)
    com.majera.intellij.codereview.bitbucket (2022.3.1.221)
    git-extended-update-index (0.1.0)
    com.intellij.plugin.adernov.powershell (2.0.10)
    zielu.gittoolbox (212.9.7)
    com.microsoft.tooling.msservices.intellij.azure (3.66.1-2022.2)
    MavenRunHelper (4.20.213.3714.1)

Kotlin: 222-1.7.10-release-334-IJ3345.90
````

````
java.lang.ClassCastException: class com.intellij.kubernetes.helm.tgz.TgzHandler cannot be cast to class com.github.b3er.idea.plugins.arc.browser.base.BaseArchiveHandler (com.intellij.kubernetes.helm.tgz.TgzHandler is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5c4dad47; com.github.b3er.idea.plugins.arc.browser.base.BaseArchiveHandler is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @37e6648c)
	at com.github.b3er.idea.plugins.arc.browser.base.BaseArchiveFileSystem.getHandler(BaseArchiveFileSystem.kt:21)
	at com.github.b3er.idea.plugins.arc.browser.base.BaseArchiveFileSystem.getHandler(BaseArchiveFileSystem.kt:13)
	at com.intellij.openapi.vfs.newvfs.ArchiveFileSystem.getArchiveRootAttributes(ArchiveFileSystem.java:138)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findRoot(PersistentFSImpl.java:1354)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findRoot(PersistentFSImpl.java:58)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.extractRootFromPath(VfsImplUtil.java:158)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.prepare(VfsImplUtil.java:135)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:47)
	at com.github.b3er.idea.plugins.arc.browser.base.BaseArchiveFileSystem.findFileByPath(BaseArchiveFileSystem.kt:70)
	at com.intellij.openapi.vfs.newvfs.ArchiveFileSystem.getRootByLocal(ArchiveFileSystem.java:36)
	at com.github.b3er.idea.plugins.arc.browser.base.BaseArchiveFileSystem.getArchiveRootForLocalFile(BaseArchiveFileSystem.kt:35)
	at com.github.b3er.idea.plugins.arc.browser.formats.sevenzip.SevenZipPsiFileNode.getChildrenImpl(SevenZipPsiFileNode.kt:14)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.doGetChildren(AbstractPsiBasedNode.java:92)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.getChildren(AbstractPsiBasedNode.java:76)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:37)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:383)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:299)
	at com.intellij.ui.tree.StructureTreeModel$Node.isModelLeaf(StructureTreeModel.java:557)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:335)
	at com.intellij.ui.tree.LeafState.get(LeafState.java:64)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:574)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:547)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:440)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:406)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:314)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:203)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:181)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:481)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
````

**Comment by b3er** [comment]
Hi! Do you use kubernetes plugin from jetbrains?
Try to disable it and check if its working, also, provide the file name on when this exception is occurred

**Comment by survivant** [comment]
next time I get the error, I'll check the name

here the plugins installed
````
Archive Browser (0.32)
Azure Toolkit for IntelliJ (3.66.1-2022.2)
Bitbucket Pull Requests (2022.3.1.221)
Git extended update-index (0.1.0)
GitToolBox (212.9.7)
Go Template (222.3345.108)
Kubernetes (222.3345.108)
Maven Helper (4.20.213.3714.1)
PowerShell (2.0.10)
Android (2021.2.1 Final.222.3345.90)
Smali Support (222.3345.90)
Ant (222.3345.90)
Gradle (222.3345.90)
Gradle Extension (222.3345.90)
Maven (222.3345.90)
Maven Extension (222.3345.90)
Code Coverage for Java (222.3345.90)
Database Tools and SQL (222.3345.90)
Docker (222.3345.90)
FTP/SFTP/WebDAV Connectivity (ex. Remote Hosts Access) (222.3345.90)
GlassFish (222.3345.90)
Tomcat and TomEE (222.3345.90)
WildFly (222.3345.90)
HTML Tools (222.3345.90)
Refactor-X (222.3345.90)
XPathView + XSLT (222.3345.90)
XSLT Debugger (222.3345.90)
IDE Settings Sync (222.3345.90)
Settings Repository (222.3345.90)
Angular and AngularJS (222.3345.90)
JavaScript and TypeScript (222.3345.90)
JavaScript Debugger (222.3345.90)
JavaScript Intention Power Pack (222.3345.90)
Node.js (222.3345.90)
TSLint (222.3345.90)
AOP Pointcut Language (222.3345.90)
Hibernate (222.3345.90)
Jakarta EE Platform (222.3345.90)
Jakarta EE: Application Servers (222.3345.90)
Jakarta EE: Bean Validation (222.3345.90)
Jakarta EE: Contexts and Dependency Injection (CDI) (222.3345.90)
Jakarta EE: Expression Language (EL) (222.3345.90)
Jakarta EE: Messaging (JMS) (222.3345.90)
Jakarta EE: Persistence (JPA) (222.3345.90)
Jakarta EE: RESTful Web Services (JAX-RS) (222.3345.90)
Jakarta EE: Web/Servlets (222.3345.90)
Jakarta EE: WebSockets (222.3345.90)
JavaFX (222.3345.90)
JVM Microservices Frameworks (222.3345.90)
Micronaut (222.3345.90)
Persistence Frameworks (222.3345.90)
Quarkus (222.3345.90)
Reactive Streams (222.3345.90)
Spring (222.3345.90)
Spring Boot (222.3345.90)
Spring Cloud (222.3345.90)
Spring Data (222.3345.90)
Spring Initializr (222.3345.90)
Spring Integration Patterns (222.3345.90)
Spring Messaging (222.3345.90)
Spring Security (222.3345.90)
Spring Web (222.3345.90)
Spring WebSocket (222.3345.90)
Eclipse Keymap (222.3345.90)
NetBeans Keymap (222.3345.90)
Visual Studio Keymap (222.3345.90)
Ktor (222.3345.90)
Gherkin (222.3345.90)
Groovy (222.3345.90)
Kotlin (222-1.7.10-release-334-IJ3345.90)
Markdown (222.3345.90)
Properties (222.3345.90)
Shell Script (222.3345.90)
YAML (222.3345.90)
Endpoints (222.3345.90)
gRPC (222.3345.90)
OpenAPI Specifications (222.3345.90)
Protocol Buffers (222.3345.90)
Plugin DevKit (222.3345.90)
Remote Development Gateway (222.3345.90)
CSS (222.3345.90)
Less (222.3345.90)
Sass (222.3345.90)
Stylus (222.3345.90)
W3C Validators (222.3345.90)
UI Designer (222.3345.90)
FreeMarker (222.3345.90)
Haml (222.3345.90)
Jakarta EE: Server Pages (JSP) (222.3345.90)
Thymeleaf (222.3345.90)
Velocity (222.3345.90)
Cucumber for Groovy (222.3345.90)
Cucumber for Java (222.3345.90)
JUnit (222.3345.90)
TestNG (222.3345.90)
Windows 10 Light Theme (222.3345.90)
Lombok (222.3345.90)
Git (222.3345.90)
GitHub (222.3345.90)
Mercurial (222.3345.90)
Perforce Helix Core (222.3345.90)
Subversion (222.3345.90)
Bytecode Viewer (222.3345.90)
Code With Me (222.3345.90)
Copyright (222.3345.90)
Dependency Structure Matrix (222.3345.90)
Design Tools (222.3345.90)
Diagrams (222.3345.90)
Eclipse Interoperability (222.3345.90)
EditorConfig (222.3345.90)
Grazie (222.3345.90)
HTTP Client (222.3345.90)
IDE Features Trainer (222.3345.90)
IDE Features Trainer: Git Lessons (222.3345.90)
IntelliLang (222.3345.90)
Java Bytecode Decompiler (222.3345.90)
Java Internationalization (222.3345.90)
Java Stream Debugger (222.3345.90)
Machine Learning Code Completion (222.3345.90)
Machine Learning in Search Everywhere (222.3345.90)
Package Checker (222.3345.90)
Package Search (222.3345.90)
Performance Testing (222.3345.90)
Qodana (222.3345.90)
Recommenders for Java and Python (222.3345.90)
Shared Project Indexes (222.3345.90)
Space (222.3345.90)
Task Management (222.3345.90)
Terminal (222.3345.90)
TextMate Bundles (222.3345.90)
Time Tracking (222.3345.90)
Toml (222.3345.90)
WebP Support (222.3345.90)
ZKM-Unscramble (222.3345.90)
````
